-- MySQL Script generated by MySQL Workbench
-- Wed 08 Jun 2022 11:23:29 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Paciente` (
  `idPaciente` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Numero_saude` INT NULL,
  `CPF` INT NULL,
  `Dta_nasc` INT NULL,
  `RG` INT NULL,
  `Sexo` VARCHAR(4) NULL,
  `Nome_mae` VARCHAR(45) NULL,
  `CEP` INT NULL,
  `Logradouro` VARCHAR(45) NULL,
  `Cidade` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NULL,
  `Complemento` VARCHAR(45) NULL,
  PRIMARY KEY (`idPaciente`, `Nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Material` (
  `codMaterial` INT NOT NULL,
  `NomeMaterial` VARCHAR(45) NULL,
  `Qtd` INT NULL,
  `Num_Sala` INT NULL,
  PRIMARY KEY (`codMaterial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Exame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Exame` (
  `idExame` INT NOT NULL,
  `tipoExame` VARCHAR(45) NULL,
  `DataExame` INT NULL,
  PRIMARY KEY (`idExame`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
